version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
